name: Compile U-Boot

on:
  push:
    branches:
      - "develop"
  pull_request:
    branches:
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
          sudo apt-get install -y gcc-arm-linux-gnueabihf
        shell: bash

      - name: Compile U-Boot for Marsboard A20
        run: |
          make clean
          make CROSS_COMPILE=arm-linux-gnueabihf- Marsboard_A20_defconfig
          make CROSS_COMPILE=arm-linux-gnueabihf-

      - uses: actions/upload-artifact@v3
        with:
          name: Marsboard_A20
          path: |
            *.bin
            *.img