name: Compile U-Boot

on:
  push:
    branches:
      - "develop"
  pull_request:
    branches:
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
        shell: bash

      - name: Compile U-Boot for Marsboard A20
        run: |
          make CROSS_COMPILE=arm-linux-gnueabihf- Marsboard_A20_defconfig
          make CROSS_COMPILE=arm-linux-gnueabihf-
        working-directory: path/to/u-boot # Replace with the actual path to your U-Boot source code
